ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/node_modules node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/ui/node_modules packages/ui/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/ui/node_modules packages/ui/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/web-server-core/node_modules packages/web-server-core/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/web-client/node_modules packages/web-client/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/ui-core-presenters/node_modules packages/ui-core-presenters/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/web-core/node_modules packages/web-core/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/apps/market-service/node_modules apps/market-service/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/apps/e2e/node_modules apps/e2e/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/ui-core-types/node_modules packages/ui-core-types/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/apps/mock-server/node_modules apps/mock-server/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/packages/eslint-config/node_modules packages/eslint-config/node_modules
ln -s /Users/bhavidhingra/Github/BitGo/bitgo-ui/apps/app/node_modules apps/app/node_modules
